### ISSUE TITLE
API Endpoints

### ISSUE THREAD

**Issue by seanthepottingshed** [JackHaK/TMF#10]
@JackHaK 

All the API end points throws the following error:

```
syntax error, unexpected end of file
--
in api.php (line 36)

```

eg:

* http://gta.humbleandkind.co.uk/api/refdata/categories

**Comment by JackHaK** [comment]
Apologies, i forgot a semi colon when uploading the file. fixed.

**Comment by seanthepottingshed** [comment]
@JackHaK 

Cheers!
