### ISSUE TITLE
Course API Endpoints Broken

### ISSUE THREAD

**Issue by seanthepottingshed** [JackHaK/TMF#16]
@JackHaK 

The following endpoints are broken:

* http://gta.humbleandkind.co.uk/api/courses
* http://gta.humbleandkind.co.uk/api/courses/1

**Comment by PeteHaK** [comment]
Fixed - sorry Sean - Github versioning issues !!

**Comment by seanthepottingshed** [comment]
@PeteHaK 

No worries, totally understand. If an invalid course id is passed into course details endpoint, eg:

* http://gta.humbleandkind.co.uk/api/courses/1 

... the script explodes. Hopefully an invalid id should never be passed, however it may be worth handling this edge case just in case.

**Comment by PeteHaK** [comment]
Got no error handling in any of the services as yet - we're cranking them out MVP and will go back and add the error handling later

**Comment by PeteHaK** [comment]
should have added - the script explodes cos the Laravel setup is set to debug mode - you are actually getting HTML error handling screens at the moment

**Comment by seanthepottingshed** [comment]
@PeteHaK 

No worries.
