### ISSUE TITLE
Dev Version of Integration Tier

### ISSUE THREAD

**Issue by seanthepottingshed** [JackHaK/TMF#19]
@JackHaK @PeteHaK 

Long time no speak - I hope all is well with you both!

I'm finally getting around to pulling courses into the `release` version of the website from the Integration Tier, however the following endpoints are broken on the development version:

* http://gtadev.humbleandkind.co.uk/api/events
* http://gtadev.humbleandkind.co.uk/api/refdata/categories

Would you be able to advise further?

**Comment by JackHaK** [comment]
Hi Sean,

What seems to be the problem with the end points?

Jack Johnson.

On 12 Oct 2018, at 11:48, Sean Davidson <notifications@github.com<mailto:notifications@github.com>> wrote:


@JackHaK<https://github.com/JackHaK> @PeteHaK<https://github.com/PeteHaK>

Long time no speak - I hope all is well with you both!

I'm finally getting around to pulling courses into the release version of the website from the Integration Tier, however the following endpoints on the development version:

  *   http://gtadev.humbleandkind.co.uk/api/events
  *   http://gtadev.humbleandkind.co.uk/api/refdata/categories

Would you be able to advise further?

**Comment by seanthepottingshed** [comment]
@JackHaK 

Thanks for an incredibly quick response!

* http://gtadev.humbleandkind.co.uk/api/events - returns an empty array
whereas http://gta.humbleandkind.co.uk/api/events - returns an array of events

* http://gtadev.humbleandkind.co.uk/api/refdata/categories - throws an `NotFoundHttpException`,
whereas http://gta.humbleandkind.co.uk/api/refdata/categories - returns an array of categories

**Comment by JackHaK** [comment]
How peculiar...

I’ll look into it this afternoon.

Jack Johnson.

On 12 Oct 2018, at 11:55, Sean Davidson <notifications@github.com<mailto:notifications@github.com>> wrote:


@JackHaK<https://github.com/JackHaK>

Thanks for an incredibly quick response!

  *   http://gtadev.humbleandkind.co.uk/api/events - returns an empty array
whereas http://gta.humbleandkind.co.uk/api/events - returns an array of events

  *   http://gtadev.humbleandkind.co.uk/api/refdata/categories - throws an NotFoundHttpException,
whereas http://gta.humbleandkind.co.uk/api/refdata/categories - returns an array of categories

**Comment by seanthepottingshed** [comment]
@JackHaK 

No worries, thanks - really appreciated. Do you know off hand if the `gtadev` version has the new Adminstrate course categories in it?

**Comment by PeteHaK** [comment]
Hi Sean - Jack is on Customer site at the moment but we've checked and the issues were in data. When we created the development instance we didn't re-inflate all of the data. I've re-inflated reference data and i've inflated a particular course and the two end points mentioned above work OK.

The Development instance points to a development instance of Administrate so it doesn't contain the production courses. We've been trying to get Administrate to copy production across but they don't seem to want to - in the mean time I'll give you access to the Development Adminstate which might help.

Let me know if you need anything

**Comment by seanthepottingshed** [comment]
@PeteHaK 

Excellent, both the endpoints are working on `gtadev` now!

Is it OK if I continue to use the `production` version until such times as the Adminstrate data is copied across?

Obviously easier to work with a larger set of data to test filtering etc.

**Comment by PeteHaK** [comment]
Can you just be sure if you use production services that you do not call any services that would change data - i.e. be careful

We probably need a bit of a discussion because api/events will give you any events scheduled in the future BUT not courses with no scheduled events - can you be clear what you need?

**Comment by seanthepottingshed** [comment]
@PeteHaK 

I'm not calling anything at all at the moment, simply displaying data in the `release` version of the site here:

* https://gta.tps.digital/courses

...and trying to determine what information I still need to retrieve from the API per a course in order to populate the data I'm currently faking. As regards your last point I will need to discuss with Josh before getting back to you.

**Comment by seanthepottingshed** [comment]
@JackHaK 

The Categories API endpoint is still throwing `NotFoundHttpException` on `gtadev`:

* http://gtadev.humbleandkind.co.uk/api/refdata/categories

Would you be to advise me further please?

**Comment by joshgosselin** [comment]
@PeteHaK @JackHaK have the data fields in the courses in the new administrate been updated? Adam wanted to remove benefits, method and add course_content, prerequisites, course_overview and a couple of other changes. If so then obviously these will need to be reflected in the API. 


@PeteHaK our expectation is that the integration tier will handle the logic to show courses which need to be displayed but don't yet have an event. I'm not sure if there needs to be a flag in administrate to allow them to set courses to show at the end of the listing with request info. 

As you say probably worth a discussion when you are next free Pete so we are all on the same page.

**Comment by PeteHaK** [comment]
Josh,

 

We’ve just added the fields Sean asked for last week. We’re not aware of the changes Adam wants to make.

 

Tell us what Fields you want pulled through and we’ll change the integration tier – should be a few minutes to change.

 

Pete

**Comment by PeteHaK** [comment]
Sorry Sean – that’s because we re-inflate the dev integration tier to cater for the new Event fields and forgot to re-inflate ref data – again.

 

Should be fixed now.

 

Is this happens the URL to re-inflate is:

 

http://gtadev.humbleandkind.co.uk/refdata/categories/inflate

 

Pete

**Comment by joshgosselin** [comment]
I have attached the latest 'template' adam created for courses, my understanding was that this was one of the first tasks to be implemented in the clone of administrate. I'm not sure if that was the final version will need to clarify with Adam but our build reflects this structure. So once the administrate data structure is update it should be fairly linear connecting the two. 

@seanthepottingshed can you specify if there are any additional fields you need 


[Course template - review document.docx](https://github.com/JackHaK/TMF/files/2478382/Course.template.-.review.document.docx)

**Comment by seanthepottingshed** [comment]
@PeteHaK 

Thanks for inflating categories for me and passing on the URL - appreciated.

**Comment by seanthepottingshed** [comment]
@joshgosselin 

The only field I can think of which has been overlooked is `is_featured` boolean used to determine if a course is to be displayed on the homepage of the website.

Here is a full list of fields I currently have in the table as per agreed designs, with corresponding data provided via API endpoints:

* `title` -> provided as `title`
* `slug` -> generated from `title`
* `summary` -> provided as `summary`
* `length` -> provided as `length`
* `original_url` -> was provided as `coursePage` now missing
* `start_date` -> was provided as `courseDate` now missing
* `date_string` -> created from `start_date` datetime
* `date_integer` -> created from `start_date` datetime
* `cpd_points` -> **missing**
* `cost` -> was provided as `coursePrice` now missing
* `location` -> **missing**
* `introduction` -> provided as `introduction`
* `course_content` -> **missing**
* `topics` -> provided as `topics`
* `prerequisites ` -> **missing**
* `course_overview` -> **missing**
* `downloads` -> **missing**
* `useful_links` -> **missing**
* `tutors` -> **missing**
* `partners` -> **missing**
* `is_featured` -> **missing**

**Comment by PeteHaK** [comment]
Going to close this issue and re-open specific issue on Course fields
