### ISSUE TITLE
Course / Event Models administrateEventJSON

### ISSUE THREAD

**Issue by seanthepottingshed** [JackHaK/TMF#20]
@JackHaK @PeteHaK 

Is it possible to make `administrateEventJSON` visible so that I can access this data via the API endpoints?

**Comment by seanthepottingshed** [comment]
If the above isn't possible of you'd prefer not to, would it be possible to pass the following values to the API endpoints:

* `related_courses` - JSON object of Ids
* `topics` - as it appears in `adminstrateEventJSON`
* `introduction` - as it appears in `adminstrateEventJSON`
* `allowable_tutors` - would it be possible for this to pass a JSON object as follows:

```js
[
    {
        name : 'Example Tutor',
        photo: 'https://placekitten.com/200/200',
        profile: 'Plain text string'
     },
    {
        name : 'Another Tutor',
        photo: 'https://placekitten.com/200/200',
        profile: 'Plain text string'
    }
]
```

* `location_id` - would it be possible for this to return the name of the related Location?

**Comment by PeteHaK** [comment]
Hi sean - we've added introduction, topics, method and benefits to the course JSON - we have also tweaked the EVENT api so it now returns the Course JSON related to the Event - we've done this in DEV at the moment and will trigger an inflate to give you a better range of courses

**Comment by PeteHaK** [comment]
We're looking at related_courses and allowable_tutors now

**Comment by seanthepottingshed** [comment]
@PeteHaK @JackHaK 

You're absolute **LEGENDS**.

I'm actually off now to collect my son from school, but will carry on first thing Monday morning. Have a fantastic weekend.

**Comment by PeteHaK** [comment]
Closed and replaced with specific tutors issue
